# service-registry/src/main/resources/application.yaml
spring:
  application:
    name: service-registry

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://localhost:9000  # ← Fix this